55 add translation to length
vini-barba/class-validator-translator pull request #117
Opened 2022-10-09 17:59 UTC by bigotto

2022-10-09 18:03 UTC, bigotto commented on src/messages/length/length.ts
> +      : 'LenthBeetween',
@vini-barba  if you found a better way to do this, we change! :)

2022-10-18 13:24 UTC, vini-barba requested changes

2022-10-18 13:24 UTC, vini-barba commented on jest.config.ts
> +  verbose: true,
```suggestion
// verbose: undefined,
```

2022-10-18 13:24 UTC, vini-barba commented on src/config/locales/pt.json
> +  "LengthEach": "{{property}} deve ser  maior ou igual a {{constraint1}} e menor ou igual a {{constraint2}} caracteres"
```suggestion
  "LengthEach": "{{property}} deve ser maior ou igual a {{constraint1}} e menor ou igual a {{constraint2}} caracteres"
```

2022-10-19 01:14 UTC, bigotto commented on jest.config.ts
> +  verbose: true,
FIxed in last commit

2022-10-24 16:26 UTC, vini-barba approved these changes

2022-10-24 16:27 UTC, merged