feat(isemail): creating only file
vini-barba/class-validator-translator pull request #86
Opened 2022-09-21 16:48 UTC by bigotto

2022-09-22 01:02 UTC, bigotto commented on src/messages/isEmail/isEmail.spec.ts
> +    expect(got).toBe(want);
There is a problem here. @vini-barba can you look it?

2022-09-22 10:48 UTC, bigotto commented on src/messages/isEmail/isEmail.spec.ts
> +    expect(got).toBe(want);
Solved!!

2022-10-05 15:19 UTC, bigotto commented
@vini-barba resolved conflict! Can u check it again?

2022-10-05 15:20 UTC, bigotto commented on src/config/locales/pt.json
> +  "IsMongoId": "O valor {{value}} não é um MongoID válido",
```suggestion
  "IsMongoId": "{{property}} deve ser um mongodb id",
```

2022-10-05 19:14 UTC, vini-barba requested changes

2022-10-05 19:14 UTC, vini-barba commented on src/messages/isEmail/isEmail.spec.ts
> +describe('Contains', () => {
```suggestion
describe('IsEmail', () => {
```

2022-10-05 19:14 UTC, vini-barba commented on src/config/locales/pt.json
> +  "IsEmail": "{{property}} deve ser um email"
```suggestion
  "IsEmail": "{{property}} deve ser um email",
```

2022-10-05 19:20 UTC, merged

2022-10-05 19:21 UTC, vini-barba commented
closes #29 #100